 
name: Build and Deploy to iGEM

on:
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'iGEM-deploy')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false    
      
      - name: Install and Test
        run: |
          npm install
          npm run test

      - name: Preprocess
        run: npm run prestart

      - name: Build
        run: npm run build

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - run: pip install igem-wikisync
      - run: python wikisync.py
        env:
          IGEM_USERNAME: ${{ secrets.IGEM_USERNAME }}
          IGEM_PASSWORD: ${{ secrets.IGEM_PASSWORD }}

      - run: cat upload_map.yml