 
name: Build and Deploy to Github

on:
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      
      - name: Install and Test
        run: |
          npm install
          npm run test

      - name: Github Fix
        run: sh utils/github.io_fix.sh

      - name: Preprocess
        run: npm run prestart

      - name: Build
        run: npm run build

      - run: git status

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          allow_empty_commit: true